### ISSUE TITLE
Send response to client with session token and user's nickname

### ISSUE THREAD

**Issue by tking2096** [tking2096/cs414-f17-301-chessire-coders#199]
#176

**Comment by camja014** [comment]
I think I'm going to create a couple new utility classes for hashing passwords and generating the tokens.

**Comment by camja014** [comment]
Also, the session management on the server probably needs to be re-designed. It was kinda thrown together.

I'm looking into how to do that right now. I'll be working on this in my branch [here](/tking2096/cs414-f17-301-chessire-coders/tree/cameron/update/session-management).

Please look at it (when I actually have something), let me know what you think, and feel free to push updates to it.
