### ISSUE TITLE
Show opponent name in games & invite lists.

### ISSUE THREAD

**Issue by tking2096** [tking2096/cs414-f17-301-chessire-coders#292]

**Comment by camja014** [comment]
The opponent name is displayed in the games list as of #287

**Comment by tking2096** [comment]
Oh ok great. I think we should still make a change — what about displaying

Opponent Name (start date)

**Comment by camja014** [comment]
Yeah, sounds good to me

**Comment by camja014** [comment]
I say we don't worry about this. The current version might not look the best, but in trying to change it to use date I discovered the date is not being initialized somewhere up the chain, and it breaks just about everything.
